#!/bin/sh

case $1 in
    clean)
        for f in *.tex; do
            latexmk -CA $f
        done
        ;;
    pdf)
        for f in *.tex; do
            latexmk -pdf $f
        done
        ;;
esac
